[package]
name = "riscvjit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "*"
goblin = "0.10.2"
bitfield = "0.19.3"
bitflags = "2.9.4"
